### ISSUE TITLE
[request] Add support for "hl.q" parameter

### ISSUE THREAD

**Issue by eduardomps** [php/pecl-search_engine-solr#28]
Hello,

I'd like to request that the library supported overriding the "hl.q" parameter, as stated on the solr ref. guide:

<html><body>

hl.q | (q=) | A  query to use for highlighting. This parameter allows you to highlight  different terms than those being used to retrieve documents.
-- | -- | --

</body>
</html>

We have a couple of cases where a query is made against a copy field which does not return highlights, but another one does because of the analyzers on each are different (for highlighting purposes we could force the use of the second one)

**Comment by omars44** [comment]
@eduardomps released on version 2.7.0, thanks for your request
