### ISSUE TITLE
Not support PHP 8

### ISSUE THREAD

**Issue by maxsky** [php/pecl-search_engine-solr#35]

**Comment by peterweck** [comment]
Looking that recent commits it looks like this is fixed on the master. Can we get a release tag that included these fixes?

**Comment by kwfinken** [comment]
The list of Deprecations that I am getting is a little longer, but all have to do with return type compatibility or the serialization interface.

- Deprecated: Return type of SolrDocument::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::offsetExists($fieldName) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::offsetGet($fieldName) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::offsetSet($fieldName, $fieldValue) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::offsetUnset($fieldName) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrDocument::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrObject::offsetExists($property_name) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrObject::offsetGet($property_name) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrObject::offsetSet($property_name, $property_value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: Return type of SolrObject::offsetUnset($property_name) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in Unknown on line 0
- Deprecated: SolrDisMaxQuery implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in Unknown on line 0
- Deprecated: SolrDocument implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in Unknown on line 0
- Deprecated: SolrModifiableParams implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in Unknown on line 0
- Deprecated: SolrQuery implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in Unknown on line 0

**Comment by bix0r** [comment]
Fixed in release 2.6.0
