### ISSUE TITLE
Solr compilation and libcurl error on systems with multiarch support

### ISSUE THREAD

**Issue by dpushkarev** [php/pecl-search_engine-solr#46]
**Description:**
I try to compile solr 2.6.0 but ./configure fails with error

**Actual result:**
`configure: error: Please reinstall the libcurl distribution - easy.h should be in <curl-dir>/include/curl/`

**Expected result:**
Extension should be installed

**Additional info:**
SOLR 2.6.0
PHP 8.0
Platforms:
- Debian 10 64 bits
- Debian 11 64 bits
- Ubuntu 20.04 64 bits
- Ubuntu 22.04 64 bits
*On ReaHat Compatible systems error does not appear.

Before compilation I installed required dependency  `libcurl4-gnutls-dev` via apt-get
I found `libcurl4-gnutls-dev` is installed in `/usr/include/x86_64-linux-gnu/curl` when ./configure expect it in `/include/curl`. The script does not detect the multiarch architecture.
I consider that extension should not be installed with using configure flags on popular OS, anyway I tried to use `--with-curl=/usr/include/x86_64-linux-gnu/curl` but it did not work.

**Comment by bix0r** [comment]
@dpushkarev Did you see pull request #44 ? 

I am hoping that one would fix this issue. Personally I use Debian based OS and that fix helps me.

**Comment by dpushkarev** [comment]
I did not, thank you!
How do you consider, will it cover OS with ARM architecture. I got the same error on Ubuntu 22.04 ARM with a few exceptions. `libcurl4-gnutls-dev` was installed in `/usr/include/aarch64-linux-gnu/curl` instead of `/usr/include/x86_64-linux-gnu/curl`

**Comment by bix0r** [comment]
@dpushkarev Did you get this arm error using the code in the PR?

I just tested it on a debian11 aarch64 and it worked. Curl installed in `/usr/include/aarch64-linux-gnu/curl`.

**Comment by omars44** [comment]
released on version 2.7.0
