### ISSUE TITLE
Missing Windows DLLs

### ISSUE THREAD

**Issue by stronk7** [php/pecl-search_engine-solr#51]
Hi,

first of all, let me apologise if this is not the correct place to ask about this. I'm a little bit confused about issues here, in bugs.php.net or if this is something to ask about to PECL's windows maintainers.

Basically the question is about https://pecl.php.net/package/solr missing the Windows (ddl) packages for latest release. I've been looking all over the place to see if there was any reason for them not being available, but have failed to find anything.

Hence, asking here. Is there any reason for them to be missing?

Without them, we are locked out from testing anything under Windows with actual PHP 8.x versions and just it would be great to know a little more, in order to see which options we have.

Thanks for all the hard work and ciao :-)

**Comment by Jan-E** [comment]
@cmb69 What is the status of the machine for compiling Windows extensions?
@stronk7 You could use the extensions in my builds: https://www.apachelounge.com/viewtopic.php?t=6359

**Comment by stronk7** [comment]
Thanks @Jan-E,

and, yep... I've been looking to other various extensions and it seems that since October 2022 (aprox) there aren't Windows builds for any in general (redis, apccu, igbinary, sqlsrv...).

Ciao :-)

**Comment by omars44** [comment]
thanks to @Jan-E, PECL Solr 2.6.0 is available as a windows DLL on the Apache Lounge Forum, that solution works for now, until we get an update from the windows team.

**Comment by macintoshplus** [comment]
Hi,

The prebuild DLLs for this extension are available here: https://phpext.phptools.online/extension/search-engine/solr-412

**Comment by omars44** [comment]
released on version 2.7.0, now found on github releases page

**Comment by cmb69** [comment]
Note that Windows DLLs are available again via https://pecl.php.net/package/solr for some time now.
