### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by bobahvas** [php/pecl-search_engine-solr#60]
Will this package support 8.3 version?
If so, when?

pecl/solr requires PHP (version >= 7.0, version <= 8.2.99), installed version is 8.3.0

thank you

**Comment by matinosal** [comment]
Hi,
I'm getting the same error and I also want to update my project to the newest official php version.

Any chances that this feature will be released in the nearest time?

Best, 
Mateusz

**Comment by bix0r** [comment]
@bobahvas @matinosal Next release will support 8.3. We are working on fixing Windows build issues. As soon as that is done the plan is to make a release.

**Comment by bobahvas** [comment]
@bix0r great news. Thank you.

**Comment by omars44** [comment]
@bobahvas released on 2.7.0
