### ISSUE TITLE
pecl solr does not install/compile with PHP 8.4

### ISSUE THREAD

**Issue by stfast** [php/pecl-search_engine-solr#80]
[root@dx1 php-8.4.1]# /usr/local/php-8.4/bin/pecl install -f solr

warning: pecl/solr requires PHP (version >= 7.4.0, version <= 8.3.99), installed version is 8.4.1
downloading solr-2.7.0.tgz ...
Starting to download solr-2.7.0.tgz (628,024 bytes)
.............................................................................................................................done: 628,024 bytes
36 source files, building
running: phpize
Configuring for:
PHP Version:             8.4
PHP Api Version:         20240924
Zend Module Api No:      20240924
Zend Extension Api No:   420240924
building in /tmp/pear/temp/pear-build-root7657n30gfvh54nE5vym/solr-2.7.0
running: /tmp/pear/temp/solr/configure --with-php-config=/usr/local/php-8.4/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gawk... gawk
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether cc accepts -g... yes
checking for cc option to enable C11 features... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -Wl,-rpath,... yes
checking for PHP prefix... /usr/local/php-8.4
checking for PHP includes... -I/usr/local/php-8.4/include/php -I/usr/local/php-8.4/include/php/main -I/usr/local/php-8.4/include/php/TSRM -I/usr/local/php-8.4/include/php/Zend -I/usr/local/php-8.4/include/php/ext -I/usr/local/php-8.4/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php-8.4/lib/php/extensions/no-debug-non-zts-20240924
checking for PHP installed headers prefix... /usr/local/php-8.4/include/php
checking if debugging is enabled... no
checking if PHP is built with thread safety (ZTS)... no

Configuring extension
checking whether to enable the Solr extension... yes, shared
checking whether to compile with solr in verbose mode... no
checking whether to enable code coverage... no
/tmp/pear/temp/solr/configure: line 5234: syntax error near unexpected token `-fprofile-arcs,'
/tmp/pear/temp/solr/configure: line 5234: `        PHP_CHECK_GCC_ARG(-fprofile-arcs,                     COVERAGE_CFLAGS="$COVERAGE_CFLAGS -fprofile-arcs")'
ERROR: `/tmp/pear/temp/solr/configure --with-php-config=/usr/local/php-8.4/bin/php-config' failed

**Comment by bilhackmac** [comment]
Awaiting _PECL_ `Solr 2.8.0`  release, you can build from _master_, it work perfectly.

```
apt-get update
apt-get install git libcurl4-openssl-dev libxml2-dev autoconf make gcc pkg-config
git clone https://github.com/php/pecl-search_engine-solr.git
cd pecl-search_engine-solr
phpize
./configure
make -j $(nproc)
make install
```

**Comment by omars44** [comment]
@stfast PR open #81
